[package]
name = "Examples"
version = "0.0.0"

[addresses]
MoonCoin = "0x61b6ec207878a636a31a5c4291a74b790cb5b7a7e14ed7f76f166146788eacf6"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "main" }
